# fly.toml app configuration file generated for pokemon-exercise on 2023-10-11T15:25:37+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pokemon-exercise"
primary_region = "ams"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.15.0"

[[services]]
  http_checks = []
  internal_port = 5000
  processes = ["app"]
