name: Health check 

on:
#  schedule:
#    - cron: '50 * * * *'
  push:
    branches:
      - master

jobs:
  ping:
    if: ${{ 'this line is removed' == 'true'}}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@fc2fe2a9ca9c9734d992431b749b79350d771fbb
        with:
          url: https://fs-pokedex-2023.fly.dev
